In [16]:
import os
import sys
from collections import defaultdict as ddict
import pandas as pd
import numpy as np
from tqdm import tqdm
from pprint import pprint

data_dir    = '/data/shire/data/NO-BACKUP/multilingual_KGQA/SMILER/data/'
tsv_files   =  os.listdir(data_dir)
lang_dict   =  ddict(lambda: ddict(int))
label_set   =  set()

for tsv_file in tqdm(tsv_files):
    if tsv_file.endswith('_train.tsv'):
        lang = tsv_file.split('_')[0]

        if lang == 'en-small':
            continue
        elif lang == 'en-full':
            lang = 'en'

        df   = pd.read_csv(data_dir + tsv_file, sep='\t')
        labels = list(df['label'])
        for lbl in labels:
            lang_dict[lang][lbl] += 1
            label_set.add(lbl)

100%|██████████| 51/51 [00:05<00:00,  9.94it/s]

In [17]:
label_dict  =  ddict(list)

for lbl in list(label_set):
    label_dict['label'].append(lbl)
    for lang in lang_dict:
        label_dict[lang].append(lang_dict[lang][lbl])
        

label_df = pd.DataFrame(label_dict)
display(label_df)

rel_freqs = [50, 100, 200, 500, 1000]

,label,ko,es,en,fa,pl,uk,it,sv,ru,pt,nl,ar,fr,de
0,no_relation,313,534,2630,208,0,68,516,27,119,363,333,322,551,458
1,has-length,0,0,1266,0,0,0,0,0,0,0,0,0,0,0
2,has-type,701,894,127645,1374,2982,247,10383,846,1085,5550,3482,758,5160,5804
3,invented-when,142,0,970,0,0,0,0,0,0,0,0,0,0,0
4,birth-place,2916,3209,88973,0,4676,0,18686,158,0,12621,7054,0,21052,18378
5,has-sibling,292,0,1430,0,0,0,0,0,0,0,0,0,0,0
6,event-year,116,14,3860,7,131,48,110,85,143,122,85,102,124,193
7,org-has-founder,303,95,12532,0,24,0,612,18,0,385,247,0,499,436
8,has-population,28,23,26201,8,1996,83,2405,929,1220,1147,10830,1057,325,449
9,has-child,569,25,3930,0,63,0,161,14,0,79,31,0,112,128
10,first-product,50,0,886,0,0,0,0,0,0,0,0,0,0,0
11,has-occupation,4101,1896,92561,923,2476,468,6900,79,3365,4397,1789,6525,7896,6152
12,has-highest-mountain,130,0,824,0,0,0,0,0,0,0,0,0,0,0
13,has-lifespan,0,0,972,0,0,0,0,0,0,0,0,0,0,0
14,org-leader,1,0,7049,0,51,0,174,4,0,146,74,0,170,128
15,loc-leader,0,11,518,0,26,0,44,2,0,24,25,0,15,32
16,has-height,0,0,939,0,0,0,0,0,0,0,0,0,0,0
17,starring,0,0,5312,0,0,0,0,0,0,0,0,0,0,0
18,is-member-of,1247,67,26298,1,682,0,1186,2,11,827,1099,16,631,1349
19,headquarters,795,494,29143,0,262,0,636,164,0,604,802,0,465,894
20,has-author,388,245,58156,0,113,0,2843,48,0,1026,386,0,1845,1103
21,has-parent,895,83,11202,0,112,0,781,99,0,339,184,0,504,764
22,has-edu,160,13,6638,10,29,3,179,5,48,67,58,316,151,254
23,won-award,179,8,7385,0,15,0,86,16,0,89,30,1,14,47
24,org-has-member,406,304,26795,0,63,0,1111,14,0,693,375,0,797,1035
25,post-code,0,0,556,0,0,0,0,0,0,0,0,0,0,0
26,has-spouse,471,13,7759,0,95,0,496,43,0,318,123,0,295,352
27,has-weight,0,0,854,0,0,0,0,0,0,0,0,0,0,0
28,eats,0,0,210,0,0,0,0,0,0,0,0,0,0,0
29,has-genre,913,746,75821,93,260,51,3243,79,404,1754,752,206,2494,1799
30,invented-by,60,0,830,0,0,0,0,0,0,0,0,0,0,0
31,has-tourist-attraction,129,0,882,0,0,0,0,0,0,0,0,0,0,0
32,from-country,2033,434,92022,0,318,0,610,45,0,1376,3685,0,1443,2999
33,has-nationality,427,0,5539,0,0,0,0,0,0,0,0,0,0,0
34,is-where,51,1308,168218,0,2265,0,9414,1736,0,7061,5668,0,8568,4698
35,movie-has-director,895,645,114474,0,192,0,13398,69,0,4347,1738,0,7773,4038

In [23]:
from datasets import load_dataset

ds = load_dataset("Babelscape/REDFM", "all_languages")

DatasetDict({
    train: Dataset({
        features: ['docid', 'title', 'uri', 'lan', 'text', 'entities', 'relations'],
        num_rows: 10337
    })
    test: Dataset({
        features: ['docid', 'title', 'uri', 'lan', 'text', 'entities', 'relations'],
        num_rows: 2551
    })
    validation: Dataset({
        features: ['docid', 'title', 'uri', 'lan', 'text', 'entities', 'relations'],
        num_rows: 2558
    })
})

In [24]:
langs = ['en', 'es', 'zh', 'ar', 'fr', 'de', 'it']

train_data = ds['train']

{'docid': '5260414-0', 'title': 'Tropico 3', 'uri': 'Q1316866', 'lan': 'de', 'text': 'Tropico 3 ist ein Wirtschaftssimulation und der dritte Teil der "Tropico"-Reihe. Das Spiel stellt damit den Nachfolger des 2003 erschienenen Spiels "Tropico 2: Die Pirateninsel" dar. "Tropico 3 "erschien am 24. September 2009 für Windows, eine Xbox-360-Version wurde knapp einen Monat später veröffentlicht. Diese Konsolenversionen stellt ein Novum in der Serie dar, die bisher nur für Windows und Macintosh erschien. Im Gegensatz zu den beiden Vorgängern wurde das Spiel nicht mehr von Take 2, sondern von Kalypso Media, die zuvor die Namensrechte an der Serie gekauft hatten, veröffentlicht. Entwickelt wurde das Spiel vom bulgarischen Team Haemimont Games. Im November 2008 war es erstmals angekündigt worden.', 'entities': [{'uri': 'Q1316866', 'surfaceform': 'Tropico 3', 'type': 'MEDIA', 'start': 0, 'end': 9}, {'uri': '+3^^http://www.w3.org/2001/XMLSchema#decimal', 'surfaceform': '3', 'type': 'NUMBER', 'start': 8, 'end': 9}, {'uri': 'Q1198141', 'surfaceform': 'Wirtschaftssimulation', 'type': 'Concept', 'start': 18, 'end': 39}, {'uri': 'None', 'surfaceform': '"Tropico"-Reihe', 'type': 'UNK', 'start': 64, 'end': 79}, {'uri': '', 'surfaceform': 'Tropico 2: Die Pirateninsel', 'type': 'UNK', 'start': 149, 'end': 176}, {'uri': '+2^^http://www.w3.org/2001/XMLSchema#decimal', 'surfaceform': '2', 'type': 'NUMBER', 'start': 157, 'end': 158}, {'uri': 'Q1316866', 'surfaceform': 'Tropico 3', 'type': 'MEDIA', 'start': 184, 'end': 193}, {'uri': '+3^^http://www.w3.org/2001/XMLSchema#decimal', 'surfaceform': '3', 'type': 'NUMBER', 'start': 192, 'end': 193}, {'uri': '2009-09-24T00:00:00Z^^http://www.w3.org/2001/XMLSchema#dateTime', 'surfaceform': '24. September 2009', 'type': 'DATE', 'start': 207, 'end': 225}, {'uri': 'Q48263', 'surfaceform': 'Xbox-360', 'type': 'ORG', 'start': 244, 'end': 252}, {'uri': '-360^^http://www.w3.org/2001/XMLSchema#decimal', 'surfaceform': '-360', 'type': 'NUMBER', 'start': 248, 'end': 252}, {'uri': 'Q75687', 'surfaceform': 'Macintosh', 'type': 'Concept', 'start': 398, 'end': 407}, {'uri': 'Q94933', 'surfaceform': 'Take 2', 'type': 'ORG', 'start': 487, 'end': 493}, {'uri': '+2^^http://www.w3.org/2001/XMLSchema#decimal', 'surfaceform': '2', 'type': 'NUMBER', 'start': 492, 'end': 493}, {'uri': 'Q26188', 'surfaceform': 'Kalypso Media', 'type': 'ORG', 'start': 507, 'end': 520}, {'uri': 'Q219', 'surfaceform': 'bulgarischen', 'type': 'LOC', 'start': 625, 'end': 637}, {'uri': 'Q787163', 'surfaceform': 'Haemimont Games', 'type': 'ORG', 'start': 643, 'end': 658}, {'uri': '2008-11-01T00:00:00Z^^http://www.w3.org/2001/XMLSchema#dateTime', 'surfaceform': 'Im November 2008', 'type': 'DATE', 'start': 660, 'end': 676}], 'relations': [{'subject': {'uri': 'Q787163', 'surfaceform': 'Haemimont Games', 'type': 'ORG', 'start': 643, 'end': 658}, 'predicate': 0, 'object': {'uri': 'Q219', 'surfaceform': 'bulgarischen', 'type': 'LOC', 'start': 625, 'end': 637}}]}

In [2]:
import dill
from helper import *

data = load_dill('../data/redfm/ar_mbert-base_stanza.dill')

In [6]:
data['validation'][1]

{'tokens': [101,
  474,
  14089,
  29759,
  53706,
  36469,
  472,
  41771,
  31291,
  29461,
  88671,
  10521,
  22885,
  37275,
  76607,
  10521,
  470,
  14921,
  20903,
  14865,
  474,
  14089,
  29759,
  78590,
  10244,
  10324,
  23786,
  14104,
  452,
  37998,
  463,
  19313,
  12337,
  10244,
  38646,
  26624,
  59152,
  40954,
  11469,
  119,
  23788,
  25177,
  10244,
  124,
  21657,
  11204,
  10244,
  70285,
  119,
  10613,
  53954,
  10558,
  25599,
  10400,
  10244,
  451,
  70384,
  470,
  11469,
  73230,
  11649,
  11795,
  12091,
  75729,
  13437,
  18870,
  13437,
  24212,
  10411,
  119,
  102],
 'tok_range': [(0, 0),
  (0, 1),
  (1, 3),
  (3, 5),
  (6, 8),
  (8, 12),
  (13, 14),
  (14, 16),
  (16, 19),
  (20, 25),
  (26, 31),
  (31, 32),
  (33, 36),
  (37, 39),
  (39, 42),
  (42, 43),
  (44, 45),
  (45, 47),
  (47, 49),
  (49, 51),
  (52, 53),
  (53, 55),
  (55, 57),
  (58, 62),
  (63, 65),
  (66, 68),
  (69, 74),
  (75, 79),
  (80, 81),
  (81, 84),
  (85, 86),
  (86, 88),
  (88, 90),
  (91, 93),
  (94, 96),
  (96, 98),
  (98, 100),
  (101, 103),
  (103, 105),
  (106, 107),
  (108, 110),
  (110, 112),
  (113, 115),
  (116, 117),
  (118, 123),
  (124, 128),
  (129, 131),
  (132, 137),
  (137, 138),
  (139, 141),
  (141, 144),
  (144, 145),
  (146, 149),
  (149, 150),
  (151, 153),
  (154, 155),
  (155, 162),
  (163, 164),
  (164, 166),
  (166, 169),
  (170, 173),
  (174, 178),
  (179, 182),
  (183, 187),
  (188, 190),
  (190, 192),
  (193, 195),
  (195, 197),
  (197, 198),
  (198, 199),
  (0, 0)],
 'e1_ids': [0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'e2_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'label': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 'dep_data': Data(x=[44, 512], edge_index=[2, 43], edge_type=[43], n1_mask=[44], n2_mask=[44]),
 'doc_text': 'كوليت روائية فرنسية الاسم الأدبي لها سيدوني غابرييل كوليت ولدت في 28 يناير 1873 بسان سافور في بويساي بيون . توفت في 3 أغسطس 1954 في باريس. انتخبت عضوة في أكاديمية غونكور عام 1910 بعد وفاة جودي جوتيه.'}

In [7]:
## create a relation dict

from datasets import load_dataset

ds = load_dataset("Babelscape/REDFM", "all_languages")

Found cached dataset redfm (/home/rdutt/.cache/huggingface/datasets/Babelscape___redfm/all_languages/1.0.0/576b7e6025452757ea5242348575c40d8d8c8d333b50445bc5909cde4bd903ee)

  0%|          | 0/3 [00:00<?, ?it/s]

In [8]:
relation_names = ['location',
'instance of',
'country',
'part of',
'follows',
'manufacturer',
'sport ',
'owned by',
'located in or next to body of water',
'member of',
'genre',
'author',
'headquarters location',
'capital',
'child',
'notable work',
'mouth of the watercourse',
'inception',
'named after',
'occupation',
'shares border with',
'participant',
'country of citizenship',
'founded by',
'place of birth ',
'replaces',
'cast member',
'league',
'characters',
'director',
'spouse',
'sibling']

In [17]:
rel_dict = ddict(int)

for rel_data in ds['train']['relations']:
    for inst in rel_data:
        rel_dict[inst['predicate']] += 1

# arrange the relations in decreasing order of frequency
rel_dict = dict(sorted(rel_dict.items(), key=lambda item: item[1], reverse=True))
print(rel_dict)

rel_map_dict = {}

for rel_name, rel_id in zip(relation_names, rel_dict.keys()):
    rel_map_dict[int(rel_id)] = rel_name

{21: 3639, 4: 3367, 0: 3297, 22: 1963, 16: 1205, 19: 1191, 25: 1180, 13: 1124, 20: 1006, 24: 923, 14: 915, 8: 745, 17: 717, 5: 621, 6: 594, 28: 585, 23: 578, 31: 572, 15: 558, 10: 526, 7: 466, 27: 443, 3: 441, 11: 438, 1: 436, 29: 391, 18: 348, 12: 333, 26: 300, 9: 296, 2: 255, 30: 203}

In [18]:
print(rel_map_dict)

json.dump(rel_map_dict, open('../data/redfm/relations_dict.json', 'w'), indent=4)

{21: 'location', 4: 'instance of', 0: 'country', 22: 'part of', 16: 'follows', 19: 'manufacturer', 25: 'sport ', 13: 'owned by', 20: 'located in or next to body of water', 24: 'member of', 14: 'genre', 8: 'author', 17: 'headquarters location', 5: 'capital', 6: 'child', 28: 'notable work', 23: 'mouth of the watercourse', 31: 'inception', 15: 'named after', 10: 'occupation', 7: 'shares border with', 27: 'participant', 3: 'country of citizenship', 11: 'founded by', 1: 'place of birth ', 29: 'replaces', 18: 'cast member', 12: 'league', 26: 'characters', 9: 'director', 2: 'spouse', 30: 'sibling'}

In [20]:
redfm_rel_dict = json.load(open('../data/redfm/relations_dict.json'))
print(redfm_rel_dict)

{'21': 'location', '4': 'instance of', '0': 'country', '22': 'part of', '16': 'follows', '19': 'manufacturer', '25': 'sport ', '13': 'owned by', '20': 'located in or next to body of water', '24': 'member of', '14': 'genre', '8': 'author', '17': 'headquarters location', '5': 'capital', '6': 'child', '28': 'notable work', '23': 'mouth of the watercourse', '31': 'inception', '15': 'named after', '10': 'occupation', '7': 'shares border with', '27': 'participant', '3': 'country of citizenship', '11': 'founded by', '1': 'place of birth ', '29': 'replaces', '18': 'cast member', '12': 'league', '26': 'characters', '9': 'director', '2': 'spouse', '30': 'sibling'}